/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.*;
import tela.EvaInSpace;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagem/a.jpg"));

        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane() {
            public void paintComponent(Graphics g) {
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        mrMenu = new javax.swing.JMenuBar();
        mnJanelas = new javax.swing.JMenu();
        miJogo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        mnJanelas.setText("Janelas");

        miJogo.setText("Jogo");
        miJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJogoActionPerformed(evt);
            }
        });
        mnJanelas.add(miJogo);

        mrMenu.add(mnJanelas);

        setJMenuBar(mrMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJogoActionPerformed

        JFrame tela = new JFrame("Eva In Space");

        tela.setSize(1280, 720);
        tela.setLayout(null);
        tela.setLocationRelativeTo(null);
        tela.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        EvaInSpace eva = new EvaInSpace();
        eva.setBounds(0, 0, 1280, 720);

        tela.add(eva);

        tela.addKeyListener(eva);

        tela.dispose();

        tela.setVisible(true);
    }//GEN-LAST:event_miJogoActionPerformed

    private void miSobreActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(null, "Jogo desenvolvido por Charles e Ivo para a matéria de Programação Orientada a Objetos");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem miJogo;
    private javax.swing.JMenu mnJanelas;
    private javax.swing.JMenuBar mrMenu;
    // End of variables declaration//GEN-END:variables
}

